#1 create a greeting for your program...
print('Hello user, This is a band name generator.')

#2 ask the user for the city they grew up in...
print('What city did you grow up in: ')
city =  input()

#3 ask the user for the name of a per...
print('What is the name of your pet: ')
pet = input()

#4 combine the name of their city and pet and show their band name...
print('Your band name is ' + city +  " " + pet)